title: Thanh-Tuyen Nguyen-Tran # your name (or website title) here
logo: "/images/profile_photo_round.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Corporate lawyer turned student of data. I'm currently interested in data analysis in applied neuroscience and mindfulness.  
  <br><br>
 
  <a href="https://www.linkedin.com/in/nguyentranthanhtuyen/">More info on my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: # your Google Analytics tracking ID here
