title: Thanh-Tuyen Nguyen-Tran # your name (or website title) here
logo: "/images/Profile_photo_round.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A corporate lawyer turned student of data and neuroscience. 
  <br><br>
  <a href="https://www.tuyenshares.com">Blog</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/nguyentranthanhtuyen/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: # your Google Analytics tracking ID here
