title: Thanh-Tuyen Nguyen-Tran # your name (or website title) here
logo: "/images/Profile_photo_round.png" width="50%" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Corporate lawyer turned student of data. I'm currently also interested in data analysis in mental health care and mindfulness.  
  <br><br>
 
  <a href="https://www.tuyenshares.com">More about me</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/nguyentranthanhtuyen/">View my LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: # your Google Analytics tracking ID here
