title: Thanh-Tuyen Nguyen-Tran # your name (or website title) here
logo: "/images/Profile_photo_round.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Corporate lawyer turned student of data and neuroscience. I am interested to leverage data analysis to address mental health issues. I am particularly passionate about the relationship between cognitive science and mindfulness. 
  <br><br>
 
  <a href="https://www.tuyenshares.com">More about me</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/nguyentranthanhtuyen/">View my LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: # your Google Analytics tracking ID here
